Landing, login, and register page created
ellenxxxiao/uwa-orthodontics-app pull request #15
Opened 2024-05-10 09:58 UTC by alian1001

# Created minor landing page, and complete design similar to sigma for login and register page
## Signed: This week's deliverable by Alian

When going to `localhost:3000` it will bring the tiny redirect page with a spinning wheel and a text that redirects you to `localhost:3000/login`. Click on the sign up and it will redirect to `localhost:3000/register`

2024-05-11 16:27 UTC, ellenxxxiao commented
Good work. A few things to mention:

![image](https://github.com/ellenxxxiao/uwa-orthodontics-app/assets/48679943/0dbd2ac6-9f6e-422f-b770-043c7e13aa3a)

1. Margin size. Please adjust it to follow the design. The logo needs to be positioned further towards the top.
2. Tick box for 'Remember me' should be alinged with the input box.
3. Font size for app name needs to be bigger.
4. Background color and button colours are incorrect. I will be updating the colours to tailwind config shortly and you could grab colours from there.

2024-05-11 16:38 UTC, ellenxxxiao requested changes

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/login/page.tsx
> +                    <h1 className="mx-auto font-bold tracking-wide">OrthoChat</h1>
Font size for app name needs to be bigger. Check Figma design file, it's `40px`.

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/register/page.tsx
> +"use client";
Same styling issue for the register page. Have a look at comments for login page.

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/register/page.tsx
> +                    onChange={(e) => setPassword(e.target.value)}
The way this onChange function is written causes values for the `password` and `confirm password` input boxes to change together.

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/login/page.tsx
> +                <div className="flex items-center justify-between">
Adjust margin to align with the input boxes right above it.

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/login/page.tsx
> +                <p className="text-sm text-center">Don’t have an account? <a href="/register" className="text-blue-500 hover:underline">Sign up</a></p>
On hover/click to clickable items, use colour change (e.g., from primary to primary-focus) instead of underline.

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/login/page.tsx
> +
Move the header section closer to the top of the page. Refer to Figma design.

2024-05-11 16:38 UTC, ellenxxxiao commented on src/app/login/page.tsx
> +"use client";
All below comments are for the mobile version.

2024-05-13 04:37 UTC, alian1001 commented
# Issues Resolved:
-Used tailwind config colors
-made header bigger
-change some margins
-Add hide/show password functionality
-add clear all input field for email

2024-05-13 06:20 UTC, ellenxxxiao commented
Good work! I've changed the login page to use our existing components. @alian1001 Please update the register page as well, following the changes in the login page.

2024-05-13 09:55 UTC, ellenxxxiao approved these changes

2024-05-13 09:55 UTC, merged