restyling done, edit button works
ellenxxxiao/uwa-orthodontics-app pull request #46
Opened 2024-08-14 17:20 UTC by Qiaoster

2024-08-16 01:39 UTC, alian1001 approved these changes
No direct bugs, approved

2024-08-16 15:50 UTC, ellenxxxiao requested changes

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/components/addReminder/addReminder.tsx
>          </Box>
Item is reused & styles repeated. Refactor into a component local to this page.

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/components/addReminder/addReminder.tsx
> +            >
Update `id` value

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/components/addReminder/addReminder.tsx
component folder name should be *PascalCase*

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/reminder-list/page.tsx
> +                for (let i = 0; i < reminders.length; i++) {
Use `map` instead of for loop. Refer to [Array - map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/reminder-list/page.tsx
> +                            {"ALGINERS"}
Make this a param passed in by the array `reminders` instead of hard-coding it.

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/reminder-list/page.tsx
> +                    >
Missing `key` prop. 

React requires a unique `key` prop for each child in a list when rendering multiple components. This helps React identify which items have changed, are added, or are removed, and improves performance by allowing React to only re-render the components that actually changed.

2024-08-16 15:50 UTC, ellenxxxiao commented on src/app/reminder-list/page.tsx
> +              <IconButton aria-label="back" className="bg-base-100">
Do not wrap the icon with `<IconButton>`. `<Header>` already wraps incoming icon with a `<button>`.

2024-08-16 15:50 UTC, ellenxxxiao requested changes
Changes required. Don't forget to pull from `main` and resolve any conflict before proceediing.

2024-09-22 03:32 UTC, ellenxxxiao approved these changes

2024-09-22 03:33 UTC, merged