GET POST AND DELETE Reminder API Created
ellenxxxiao/uwa-orthodontics-app pull request #58
Opened 2024-09-03 17:27 UTC by alian1001

EMAIL IS USED FOR
-Reminder update, add, delete
-Reminder when time is triggered
-This clinician has invited you to connect, if user not registered, send invitation token, otherwise add to contacts book

POST

{
  "setById": "user_2kb0nnXRX4SdwJAO5gVMyF12Xmw",
  "setForId": "user_2kit0iBGwimRaKgg3WjIIqZPAvG",
  "scheduledAt": "2024-08-20T10:00:00Z",
  "startDate": "2024-08-19T00:00:00Z",
  "endDate": "2024-09-19T00:00:00Z",
  "description": "Appointment reminder",
  "type": "APPOINTMENT",
  "intervalInDays": 30
}

PUT

{
  "id": 1,
  "setById": "user_2kb0nnXRX4SdwJAO5gVMyF12Xmw",
  "setForId": "user_2kit0iBGwimRaKgg3WjIIqZPAvG",
  "scheduledAt": "2024-08-21T10:00:00Z",
  "startDate": "2024-08-19T00:00:00Z",
  "endDate": "2024-09-20T00:00:00Z",
  "description": "Updated appointment reminder",
  "type": "APPOINTMENT",
  "intervalInDays": 60,
  "isReminderActive": true
}

DELETE

{
  "id": 1
}

Do let me know if anything else has gone wrong.

2024-09-19 14:17 UTC, ellenxxxiao requested changes
Nice work, refer to comments

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/reminder/route.ts
> +const resend = new Resend(process.env.RESEND_API_KEY);
Update the env template `.env.example` to include this key.

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/reminder/route.ts
> +      to: ["alian.haidar01@gmail.com"], // Hardcoded email recipient
accept recipient email as param

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/email/route.ts
Is this a test route? If yes you can remove it

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/login/page.tsx
Same here, remove code for testing purposes when submitting PR

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/components/emailTemplate/email-template.tsx
Try using Tailwind CSS classes.
Could also make use of React Email to use some components. Refer to https://resend.com/docs/dashboard/emails/email-templates

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/reminder/route.ts
> +export async function PUT(request: Request) {
Use `PATCH`

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/reminder/route.ts
> +      url.searchParams.get("isReminderActive") === "true";
Could be simplified by:

```typescript
import { NextRequest, NextResponse } from 'next/server';

export async function GET(
  request: NextRequest,
) {
  //...

  // get search params
  const searchParams = request.nextUrl.searchParams;
  const isActive = searchParams.get("isActive");

  //...
}

```

Refer to https://nextjs.org/docs/app/api-reference/functions/next-request#nexturl

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/reminder/route.ts
> +}
`PATCH` and `DELETE` operations should be performed on a specific reminder only, so these two endpoints should in file `api/reminder/[id]/route.ts`. The param `id` refers to the reminder ID. Refer to the `/users` endpoint.

2024-09-19 14:17 UTC, ellenxxxiao commented on src/app/api/reminder/route.ts
> +      intervalInDays
Could be converted into a type

2024-10-16 08:40 UTC, alian1001 commented on src/app/api/reminder/route.ts
> +      to: ["alian.haidar01@gmail.com"], // Hardcoded email recipient
no domain to be used. stick with hardcoded for now.

2024-10-16 15:36 UTC, merged